# https://github.com/pdmosses/agda-pages/agda-pages.mk

# Set non-default argument values before including this file in Makefile:
#
# AGDA-PAGES := ...  # relative path to AGDA-PAGES submodule/directory
# SOURCES    := ...  # Agda import include-path
# MODULES    := ...  # Agda root module name(s), separated by spaces
# PROTECT    := ...  # protected Markdown files, separated by spaces
# ...                # see below for further optional argument values
# include $(AGDA-PAGES)/agda-pages.mk
# include $(AGDA-PAGES)/agda-pages-latex.mk

##############################################################################
# HELP

# ASSUMPTION: SOURCES is a single word

# gen-latex:
# For each *.lagda.md file in SOURCES, generate *.tex in latex

##############################################################################
# GENERATE LAGDA FROM LAGDA.MD

LAGDA-MD-FILES := \
	$(sort \
	  $(shell find $(SOURCES) -name '*.lagda.md'))

LAGDA-FILES := \
	$(addprefix latex/, \
	  $(patsubst $(SOURCES)/%.lagda.md,%.lagda, $(LAGDA-MD-FILES)))

# `make gen-lagda` generates latex/*.lagda files from *.lagda.md files using pandoc

.PHONY: gen-lagda
gen-lagda: $(LAGDA-FILES)
	@echo "Generated .lagda files in latex"

$(LAGDA-FILES): Makefile | latex

latex:
	@mkdir latex && \
	cp $(AGDA-PAGES)/postprocess-latex.pl latex && \
	cp $(SOURCES)/*.agda-lib latex

latex/%.lagda: $(SOURCES)/%.lagda.md
#	Use pandoc to transform Markdown to LaTeX, adjusting heading levels:
	@pandoc -f markdown -t latex --syntax-highlighting=none \
	    --shift-heading-level-by=$(words $(wordlist 3,10, $(subst /, , ./$(*)))) \
	    -o $@ $<
#	Pandoc transforms ```agda...``` to a verbatim environment:
	@sd '\\begin\{verbatim\}' '\\begin{code}' $@
	@sd '\\end\{verbatim\}' '\\end{code}' $@
#	Pandoc transforms `...` to \texttt{...}:
	@sd '\\texttt\{' '\\AgdaRef{' $@
#	Pandoc doesn't support label prefixes:
	@sd '\\label\{' '\\label{$(*)-' $@
#	Transform [(bibkey)] references to \cite{bibkey}:
	@sd '\\href\{https://[^\{\}]*\}\{\(([^ ()]*)\)\}' \
	    '\\cite{$$1}' $@
#	Transform \cite{bibkey1}~...~\cite{bibkeyN} to \cite{bibkey1,...,bibkeyN}:
	@sd '\}~\\cite\{' ',' $@
#	Transform references to relative URLs to Section references:
#	[§ ...] -> Section~\ref{...}
	@sd '\\href\{(\.\./)*([^:\{\}]*)/index\.md\\#([^\{\}]*)\}\{§ ([^\{\}]*)\}' \
	    'Section~\\ref{$$2-$$3}' \
	    $@
	@sd '\\href\{(\.\./)*([^:\{\}]*)\.md\\#([^\{\}]*)\}\{§ ([^\{\}]*)\}' \
	    'Section~\\ref{$$2-$$3}' \
	    $@
#	[...] -> ... (Section~\ref{...})
	@sd '\\href\{(\.\./)*([^:\{\}]*)/index\.md\\#([^\{\}]*)\}\{([^\{\}]*)\}' \
	    '$$4 (Section~\\ref{$$2-$$3})' \
	    $@
	@sd '\\href\{(\.\./)*([^:\{\}]*)\.md\\#([^\{\}]*)\}\{([^\{\}]*)\}' \
	    '$$4 (Section~\\ref{$$2-$$3})' \
	    $@
	@sd '\\begin\{code\}' "\\\\begin{AgdaSuppressSpace}\n\\\\begin{code}" $@
	@sd '\\end\{code\}' "\\\\end{code}\n\\\\end{AgdaSuppressSpace}" $@
#	Transform \n--"hide"\n...\n--"/hide"\n to a hidden code block
#	where ... does not contain ":
	@sd '\n--"hide"\n([^\"]*)\n--"/hide"\n' \
	    "\n\\\\end{code}\n\\\\begin{code}[hide]\n\$$1\n\\\\end{code}\n\\\\begin{code}\n" \
	    $@
#	Remove generated empty code blocks:
	@sd '\n\\begin\{code\}\n\\end\{code\}' '' $@
#	Comment-out blank lines around code blocks:
	@sd '\n\n\\begin\{AgdaSuppressSpace\}' "\n%\n\\\\begin{AgdaSuppressSpace}" $@
	@sd '\\end\{AgdaSuppressSpace\}\n\n' "\\\\end{AgdaSuppressSpace}\n%\n" $@
#	Delete @latex and @/latex:
	@sd '@[/]?latex' '' $@

##############################################################################
# GENERATE LATEX FROM LAGDA.MD

LAGDA-INCLUDE := $(AGDA) --include-path=latex

LAGDA-QUIET   := $(LAGDA-INCLUDE) --trace-imports=0
LAGDA-VERBOSE := $(LAGDA-INCLUDE) --trace-imports=3

LATEX-FILES := $(LAGDA-FILES:.lagda=.tex)

# `make gen-latex` cleans latex, generates *.lagda files in latex,
# then generates *.tex files in latex

.PHONY: gen-latex
gen-latex: clean-latex gen-lagda $(LATEX-FILES)
	@echo "Generated .tex files in latex"

$(LATEX-FILES): Makefile | latex

latex/%.tex: latex/%.lagda
#	When lagda file contains Agda code, use agda to transform it to tex
#	then use postprocess-latex to fix arguments of \AgdaRef commands,
#	otherwise simply copy the lagda file to a tex file:
	@if grep -q '^\\begin{code}' $< ; then \
	    $(LAGDA-QUIET) --latex --latex-dir=latex $< ; \
	    perl latex/postprocess-latex.pl $@ > $@.processed ; \
	    mv $@.processed $@ ; \
	else \
	    cp $< $@ ; \
	fi

# `make clean-latex` removes all the files generated by gen-lagda and gen-latex

.PHONY: clean-latex
clean-latex:
	@rm -rf latex

.PHONY: debug-latex
export DEBUGLATEX
debug-latex:
	@echo "$$DEBUGLATEX"

define DEBUGLATEX

LAGDA: $(LAGDA)

LAGDA-MD-FILES: $(strip $(LAGDA-MD-FILES))

LAGDA-FILES:    $(strip $(LAGDA-FILES))

LATEX-FILES:    $(strip $(LATEX-FILES))

endef
